### ISSUE TITLE
Can't Open GUI of Dank null

### ISSUE THREAD

**Issue by RobertLeeMich** [p455w0rd/DankNull#103]
Title. Can't open the GUI by shift + Rclicking. Different method now or still not fixed?

**Comment by marikc0** [comment]
I have the same issue in 1.12.2 with the latest version of Dank Null as of this date.

I resolved this by setting a keybind to open nearest dank null.

Edit: The issue appears to be when you are looking at a block the shift+click doesn't work and that's why (but not when looking at open air).

**Comment by p455w0rd** [comment]
yeah..this is actually intended...you must now set a keybind (this can include mouse keys) manually..the reason it doesn't open the old way is due to getting reports of people falling to their death in certain situations (usually when crouching+placing/walking backward)..this way the player is fully responsible :)
