### ISSUE TITLE
Dank Null Randomly Empties Itself - Items Don't Stay Inside

### ISSUE THREAD

**Issue by marikc0** [p455w0rd/DankNull#108]
In 1.12.2 with the latest Dank Null as of this date items are randomly emptying from the Dank Null into the inventory (not sure what is triggering it yet). Also they don't appear to be staying in the Dank Null at other times? Maybe vanishing from it too.

**Comment by NewtonAppolonius** [comment]
Just started seeing this as well. Don't know if it is related but it's only started playing up since I upgraded to the Mk 6 version.
Quark Marble just disappears on pick up. 
Just had a thought. It's a bit anecdotal but I think I have only started seeing this bug since I broke the 3200 stack size with the Mk6

**Comment by NewtonAppolonius** [comment]
Okay I just built a new Dank Null at Tier 5
Parked the Mk6 in a crate and started using the new Mk5.

Within a very short while (about 10 stacks all with less than 64 items in them) items started  disappearing.
If I come out of the game to the Minecraft menu and then restarted all the missing items were in my inventory.

Direwolf20 1.12.2 Pack
Forge 14.23.3.2675
DankNull-1.12-1.4.33

**Comment by p455w0rd** [comment]
this was a sync issue with the docking station...should be 100% resolved in the latest version since I separated the syncing code (they used to use the same classes)..let me know if not
