### ISSUE TITLE
Dank null randomly switches blocks when using it

### ISSUE THREAD

**Issue by CharCharthemonkey** [p455w0rd/DankNull#120]
on the latest version for dank null on the tier 6 (idk if the other ones did it too) when trying to use a certian block it will just randomly switch block types without scrolling and also when using it to place items there is considerable block lag from it too

**Comment by KollinsPlays** [comment]
I have seen something like this too. Occasionally when I first start using the dank/null to place blocks, it will place some random block from it's inventory instead of the one that is selected. For me, it usually happens once and then goes back to the selected block. For instance, if I have cobble selected and start placing cobble, it will place 1 dirt then go back to placing the selected cobble.

**Comment by p455w0rd** [comment]
should be fixed with latest update
