### ISSUE TITLE
Dupe Bug With Chisels and Bits 

### ISSUE THREAD

**Issue by Vlogical123** [p455w0rd/DankNull#129]
Found an interesting bug in the way chisels and bits blocks are handled in a given dank/null. When bitting a block, it becomes recognized as "chiseled (insert block name here)". The issue is that say for example you chisel a block into stairs, and then chisel a different block into a slab, whichever one is in the dank/null will be recognized, therefore allowing you to get more bits out of a slab when you break it that would turn into a stair in the null. Now, normally this wouldn't be an issue with most blocks, however the issue lies in the ability to chisel metal blocks, say for instance diamond. By breaking off one bit from a diamond block, the block becomes chiseled diamond block, which can then be put in a dank null. However, when you take that diamond bit and break it, it goes in the dank null and is recognized as the chiseled diamond block as well.  Therefore, you could infinitely dupe the diamond bits and use them to make an infinite amount of diamond blocks in this example. In the image below, I started with one and was able to infinitely make more diamond blocks. 
![2018-07-25_10 49 40](https://user-images.githubusercontent.com/23739747/43208909-761fac40-8ff9-11e8-9563-51de55ff5e78.png)

**Comment by p455w0rd** [comment]
I just haven't had time to finish the update. I believe this is fixed in dev (and is same meta bug affecting tons of other stuff), but other things are in the middle of being rewritten. If loading up Chisels & Bits in a dev env isn't too much of a pain, I'll test today to be sure. If not, it'll have to wait till I do obf testing. I'm very close to getting a Minechem alpha released. Then I've been commissioned to do another mod which might take a while. I can, and do, work on the /dank/null update here and their. It just only gets as much attention as any of my other personal projects.

**Comment by Vlogical123** [comment]
Oh ok. Yea, thats totally fine. Don't intend on using it myself, just figured I should report it as to make sure you at least knew about it. No rush. Sounds like you have a lot on your plate.

**Comment by JoshRubini** [comment]
There is a similar (same) bug affecting Thaumcraft Vis crystals and Astral Sorcery rock crystals.

Basically, placing a Vis crystal into the /dank/null causes all further Vis crystals placed in it to become the same "type" of crystal, effectively rendering all crystals identical.  For exmple, if I place an "Ordo" crystal into the /dank/null, and then place an "Aer" crystal, the Aer crystal gets stored as an Ordo crystal, and becomes Ordo when removed.

Similarly, Astral Sorcery rock and celestial crystals become the same as the first crystal inserted, which is VERY broken as it allows you to instantly "upgrade" a low quality crystal into a perfect 900 size/purity/cutting crystal.

**Comment by p455w0rd** [comment]
Please check other issues..ffs this has been known for like a year now...if u want it fixed quicker, I can give u my paypal...otherwise u will just have to wait

**Comment by JoshRubini** [comment]
I did.  This was the post that came up, hence I did not start a new issue.  I apologize if you are getting inundated with bug reports, I simply thought I'd contribute for your benefit, and since the AS and Thaumcraft effects weren't specified above, I added them so that you'd have more information.

Thanks for the mod!

**Comment by p455w0rd** [comment]
All this has been mentioned in other issues..check closed issues for dupes!

**Comment by JoshRubini** [comment]
My apologies, the search I did didn't come up with it b/c it was labeled "potions bug".  Definitely the same issue.  Cheers! #95
