### ISSUE TITLE
Stacktrace in server console- RuntimeException  When logging in.

### ISSUE THREAD

**Issue by ProsperCraft** [p455w0rd/DankNull#138]
https://gist.github.com/ProsperCraft/06acb45b7b29fd0c51f261e283c51389

Is this fixable? it may just be journeymap serverside, I have gotten in the habit of disabling it serverside as it seems to complain in console a lot.

Caused by: java.lang.RuntimeException: java.io.NotSerializableException: java.util.WeakHashMap
	at com.google.common.base.Throwables.propagate(Throwables.java:240) ~[minecraft_server.1.12.2.jar:?]
	at p455w0rd.danknull.network.PacketConfigSync.toBytes(PacketConfigSync.java:66) ~[PacketConfigSync.class:?]

**Comment by p455w0rd** [comment]
Nope, it's on my side. It's due to using classes which don't implement `java.io.Serializable` - this shouldn't hurt anything, but I am switching to fully serializable classes (ie using `Boolean.class` over Java's native `boolean`). I'm also implementing a Serializable version of NonNullList to properly conform with the standard. Thank you for the report!

**Comment by p455w0rd** [comment]
I have a build up in my discord which should fix this (it did in my local tests in SMP)..would you care to drop by and give it a test? https://discord.gg/8g62YV7
dupe ref: #139

**Comment by p455w0rd** [comment]
curse approved FAST: https://minecraft.curseforge.com/projects/dank-null/files/2624277

**Comment by ProsperCraft** [comment]
Thank you, just in the nick of time, it made my TownCraft modpack update.

**Comment by p455w0rd** [comment]
so, fixed?

**Comment by ProsperCraft** [comment]
Will let you know as soon as I can test it, ran in to a snag with the pack with forges recommended new recommended build potion changes and it crashing Immersive Engineering.
