### ISSUE TITLE
Crash When Placing Stairs

### ISSUE THREAD

**Issue by Dayyer1** [p455w0rd/DankNull#153]
Pretty straightforward... the game crashed when I tried to place stairs that were in a dank/null.

[crash-2019-01-24_15.57.14-client.txt](https://github.com/p455w0rd/DankNull/files/2793799/crash-2019-01-24_15.57.14-client.txt)

**Comment by p455w0rd** [comment]
were they vanilla stairs?

**Comment by Dayyer1** [comment]
They were from Astral Sorcery.

**Comment by elexx** [comment]
I get the exact same stacktrace (https://paste.dimdev.org/fomeqozocu.mccrash) when placing top-slabs like below. It does not matter if I rightclick adjacent slabs or the cobblestone above. - These are vanilla slabs and vanilla cobblestone.

![2019-02-10_11 00 15](https://user-images.githubusercontent.com/221837/52532337-8467a100-2d23-11e9-9f3a-6cd3948833de.png)

**Comment by gfokkema** [comment]
Same issue in Project Ozone 3, see also #162

**Comment by p455w0rd** [comment]
So the code I'm working with currently is vastly different from the code in current versions. I'm not sure what it was causing this, but as of testing right now, it appears to be fixed in dev. ![](https://puu.sh/DDnpF/11b1fc79a7.gif)
github screwed up on the encoding: original gif here: https://puu.sh/DDnpF/11b1fc79a7.gif
