### ISSUE TITLE
EnderIO + OreDict conversion allows for Wither Skull dupe

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [p455w0rd/DankNull#170]
(Original issue: NillerMedDild/Enigmatica2Expert#968)

~~Depending on what actually adds the "itemSkull" OD entry to the game, this might be either a bug in /dank/null itself or a mod interaction issue,~~ EDIT: Apparently, Ender IO adds an "itemSkull" OD entry to every vanilla and EnderIO skull, so you can convert any head / skull to a wither skeleton skull by enabling OreDict support for wither skulls in your /dank/null and then picking the other skulls up from the ground.

I was able to reproduce this on a fresh instance with only /dank/null and Ender IO installed.

My suggestion would just be to add "itemSkull" to the OD blacklist by default so this bug doesn't occur by default on instances with EnderIO installed

**Comment by p455w0rd** [comment]
added itemSkull as a default for oreDict blacklist...thanks for the suggestion :)

**Comment by Twisted-Code** [comment]
thanks for fixing this and whatever commit added the oredict blacklist config option. Simple solution for a serious but simple problem... sorta
By that I mean, there are a ton of "normal" oredict entries that this sort of thing could potentially happen with, such as gemAll. I'm not sure what mod adds it, but it's given to things like nether quartz, emeralds, and diamonds. Have you considered making this a whitelist instead of a blacklist (or allowing the user to switch from one to the other)? It might simplify things considerably, considering that in my case there are only about 40 entries (if even that many) that I would want to allow (each corresponding to an ore) and the rest I would want to disallow (especially things like what we've discussed here). Again, just a suggestion :-)

**Comment by p455w0rd** [comment]
this is already an option..whitelist takes precendence over blacklist..so just add the items to the whitelist..
![image](https://user-images.githubusercontent.com/12187748/65373381-cb6b2c80-dc4a-11e9-84d0-3169bf959541.png)

**Comment by Twisted-Code** [comment]
How did I miss that line? I'm so sorry for my ignorance. I must've read the config like, once, while half-asleep, or something. I don't have any better explanation. Thanks, and sorry, again!

**Comment by p455w0rd** [comment]
Thanks for being objective/rational through this :) [not sarcasm...seriously...most people get offended when these things happen..nice to get someone honest]

**Comment by Twisted-Code** [comment]
I try my best. Trust me, if anyone knows how imperfect (and occasionally oblivious) I am, it's me.
And yeah, I wasn't sure, but gave the benefit of the doubt that it wasn't sarcasm ;-) (but even if it had been, I kinda deserved it and would've understood. I tend to be fairly sarcastic myself, and normally don't mind when the tables turn, so long as it's not actually hostile. I legit have a t-shirt that says "caution: may contain trace amounts of sarcasm", so that should give you a clue)
