### ISSUE TITLE
Crash after updating to 1.5.71

### ISSUE THREAD

**Issue by Ravalli03** [p455w0rd/DankNull#181]
After updating this mod, the dank null are pink/black squares (no image) and when I moved them from my backpack to hot bar, game crashed. Crash report below

https://pastebin.com/BZZp0Pid

**Comment by p455w0rd** [comment]
Can you hop on [discord](https://p455w0rd.net/discord) so I can send you a jar to test?

**Comment by p455w0rd** [comment]
They may be corrupted btw as I can only do so much.If you put the /dank/null in a vanilla inventory and take it back out (like a chest), the issue might fix itself. This is because I implemented datafixing and vanilla inventories support this. Some mods do, Lots of mods don't. The version of /dank/null I have built should be good enough to get you past the crash so you can at least try to put them in a vanilla inventory to see if the datafixer will run.

**Comment by Ravalli03** [comment]
I have never used discord, but I can look into it.

**Comment by p455w0rd** [comment]
If it's easier, I can upload the file to my server, it would just be nice to have some form of real time communication.

**Comment by p455w0rd** [comment]
this auto closed

**Comment by Frikkle** [comment]
We ran into this issue when the Enigmatica 2: Expert pack updated to 1.5.71. We solved it for now by downgrading /dank/null back to the previous version the pack was on.

Any news on a sustainable fix for this issue? We wouldn't want all E2E players to come here for support ;-)

Edit: if I can do anything to help, let me know (is what I meant to say)
