### ISSUE TITLE
1.5.71 GUI Synchronization/Keybind Issues

### ISSUE THREAD

**Issue by Danekjovax** [p455w0rd/DankNull#184]
(Originally posted at https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/206, /dank/null version 1.12.2-1.5.71)

I've recently updated to the 5.2 version of the modpack, and noticed the following issues with the /dank/nulls that I have (I have 2x Mk VI):

1) GUI seems to have a synchronization issue (not sure if it's client or server based). Items aren't all displayed and pulling items from slots will not get the displayed item, or you can pull items from what you think is an empty slot. No duping is going on as far as I can tell. Items are supposed to auto-arrange from top-left, but in this case it is not visually happening.

2) Certain places prevent you from accessing the /dank/null GUI (hotkey or crouch/right-click). It may be related to if you have a block/entity in range of your crosshairs, but not totally sure.

Screenshots attached.  Thanks.
![2019-06-22_09 49 08](https://user-images.githubusercontent.com/10191173/59965299-0a69d480-94da-11e9-8e01-1692fe486d45.png)
![2019-06-22_09 55 39](https://user-images.githubusercontent.com/10191173/59965300-0ccc2e80-94da-11e9-8cec-a5be58f38159.png)

**Comment by ghost** [comment]
I too have encountered this issue using /dank/null version 1.12.2-1.5.71

**Comment by Danekjovax** [comment]
One thing that I've noticed that seems to help a little is to click in each slot, acting like you're picking up an item from that slot, then clicking again to place it back.  Doing this may take time (especially with the upper tiers) but after closing and reopening the GUI seems to fix it for now.  Still monitoring.
![2019-06-22_16 09 07](https://user-images.githubusercontent.com/10191173/59968456-33a15980-9508-11e9-8b18-01b3762b7e27.png)

The only side effect I've seen is that I've lost most of the collected items.  Used to have 1-2k of most of the blocks listed in the screenshot, but now you see what remains.

**Comment by Danekjovax** [comment]
Not sure if this will help isolate the problem, but I've noticed items that stack to over 127 items will disappear from the list, and start causing the GUI desynch.

**Comment by gorimare64** [comment]
Don't know how much it will help, but I have encountered the same issues with version 1.12-1.4.46 in the Stoneblock 2 mod pack.

**Comment by HalestormXV** [comment]
I can further verify this and it is occurring on the current latest version: DankNull-1.12.2-1.5.71.jar
Also I can verify what @Danekjovax has said it would appear over 127 items seems to cause things to go wonk. Also it would appear if you pick up "too many" items at once it can't "keep up" maybe thus also causing the DeSync. And as for a definition of "too many" I can't really provide one cause i can;t necessarily count the stacks of items on the floor lol. But if I mine out a nice Mineshaft about 15 deep 3x3 and run down the hall to pick up all the items some are lost in the device. Currently I am using the GoldTier device.

**Comment by choekstr** [comment]
I had been running .43 for the longest time since .46 was deleting items like crazy.  once I saw new versions I upgraded immediately and they all had similar issues of destroying items, desync's, empty visuals but really there if you pull a stack out.  I am currently back on .43 until p455w0rd has a chance to sort these minor issues.  It's pretty much a must have in every pack I play and I give it the love it deserves :)

**Comment by p455w0rd** [comment]
[try dis plox](https://www.curseforge.com/minecraft/mc-mods/dank-null/files/2771911) and report back

**Comment by choekstr** [comment]
ok, .77, using the 2.156 lib seems to work great!  I have more than a stack in an emerald dank null, up to 8k of cobble and it is remaining.  I tested removing, adding in through shift click and dragging in, dropping into the world and collecting, placing items from the dank null, killing mobs and mining and collecting, and visuals look perfect and no truncating of items that I have seem so far.  It seems identical to .43 in the 15 minutes I tested so far.

I'll be playing with it a lot more today so I'll keep an eye out for any weirdness and report back if so.  Otherwise I call this a success so far!  Well done bud.
