### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by GW1986** [p455w0rd/DankNull#198]
Today when booting up my MC crashed with the following crashreport

https://pastebin.com/nz3YFYdM

Disabling /DankNull in Twitch launcher solved it, so looks like issue is at least related to DankNull

**Comment by JoshMayberry** [comment]
Same thing happened here. I used an earlier version and that fixed it for me. I think the problem is with an update in DankNull.
[DankNull-1.12-1.4.46.zip](https://github.com/p455w0rd/DankNull/files/3448957/DankNull-1.12-1.4.46.zip)

**Comment by GamertechAU** [comment]
Getting the same crash. Previous versions of the mod have been archived too which means users can't easily downgrade to fix it.

Edit: Downgrade p455w0rd's Library to .151.

p455w0rd has currently scrapped /dank/null due to hate they've been receiving from people that have never developed a thing in their lives...
https://github.com/p455w0rd/p455w0rds-Library/issues/44#issuecomment-515766052

**Comment by RepoDraghon** [comment]
I, just, can't, think, of the words to express my sorrow for the Mod Author, I know how bad it can get even though I'm not a modder... Imagine the hate people have for mods that some people might think iss cheaty like X-Ray mods. This mod lets you store tons (literally) of blocks in 1 source. I hope the OP or anyone who picks up the mantle of this mod will regain composure and have a better life from this...

BTW, it says in that link, the solution is to downgrade the Password Library file... or just uninstall Dank.

**Comment by GamertechAU** [comment]
Can confirm that the pack loads correctly with the latest /dank/null and Lib. Cheers p455w0rd
