### ISSUE TITLE
Items being deleted when using shift+click from inventory to full /dank//null

### ISSUE THREAD

**Issue by EcksEcksEcks** [p455w0rd/DankNull#205]
The title says it all really. I'm currently using a MKV DN and if I try to add something to it from my inventory by shift+click the item and the DN is full it just deletes it.

Update: Actually if I click on an item and then try to add it to the full DN it also deletes it...

**Comment by p455w0rd** [comment]
yeah..this is the point...it voids after hitting max capacity

**Comment by EcksEcksEcks** [comment]
Is there a way to change it so rather than the item/stack being deleted it just stays in your inventory?

**Comment by Twisted-Code** [comment]
Yeah, make your own mod and call it /dank/hoard.
The whole idea of this mod was/is to improve on the /dev/null item from openblocks. To go against that object's core functionality of deleting the excess items would be counterproductive, since the main idea here is NOT hoarding what you can't store.
If it keeps deleting items that you put into your red or blue dank, might I suggest either paying more attention or upgrading the size instead of complaining about the core functionality next time? The final tier, emerald/tier 6, can hold millions of items per slot before it starts deleting...
