### ISSUE TITLE
Accessing /dank/null gui while in docking station

### ISSUE THREAD

**Issue by Jakrippr** [p455w0rd/DankNull#21]
Is there a way to open up the gui while the block is on the docking station to be able to change the selected item? Thanks great job on the mod.

**Comment by p455w0rd** [comment]
Not currently and I have thought about this. The issue lies in how the GUI would be accessed. Currently to change the exctraction mode you right-click. To take the /dank/null out, you crouch+right-click. This leaves few options that aren't convoluted. I mean a keybind _could_ work, but that's not very intuitive. IF you have an idea of how I could implement this while maintaining the current functionality, I'm all ears :)

**Comment by nigrum-dente** [comment]
What about: alt+right click ?

**Comment by StickmansPub** [comment]
Is this working at this time? I put mine on the docking station and right-clicking it won't open the GUI.

**Comment by p455w0rd** [comment]
nope..i've temporarily disable it until the rewrite
