### ISSUE TITLE
Dank/Null Not being picked up by Tomb Many Graves

### ISSUE THREAD

**Issue by caighan** [p455w0rd/DankNull#210]
I hesitate to say this is an issue with dank null vs tomb many graves. However it only started having the problem being picked up by the gravestone mod after this recent spurt of updates that had all the bugs. It will successfully drop on the ground by the gravestone but it does not get picked up in the gravestone. Which has made for a lost dank/null a few times. if you think this should be posted in tomb many graves page let me know. thanks

**Comment by Morpheus1101** [comment]
tomb many graves is at fault here if the dank/null isnt being picked up when the grave is made on death.

**Comment by bibo38** [comment]
Seems not to be a problem with TombManyGraves, but with /dank/null.

Using **/dank/null Version 1.7.84 or higher** (tested with p455w0rdslib 2.2.159) this bug doesn't appear using TombManyGraves 4.2.0.
Using /dank/null Version 1.6.80 (previous release) the bug is present using the same TombManyGraves version (tested with p455w0rdslib 2.2.156)
