### ISSUE TITLE
Removing DankNull from AE2 system

### ISSUE THREAD

**Issue by Pixel1011** [p455w0rd/DankNull#211]
accidentally shift clicked my mark 4 danknull into my ae2 system and now i am unable to remove it
i have no idea if its a problem with danknull or ae2 but im just going to put this here for now

i had a good 1k+ cobble, 19 sand, a bunch of rocks such as granite/diorite inside of it

**Comment by Pixel1011** [comment]
welp managed to get it out with a export bus and a fuzzy card, still doesnt make sense why i couldnt remove it from the terminal

**Comment by Twisted-Code** [comment]
it might be something to do with NBT handling. I had a similar problem with someone on my server, and I know things get a little dicey when you put objects with NBT into other objects with NBT (e.g. a dank into a storage cell). That said, it doesn't sound like yours had nearly the data complexity I would expect to cause that to happen; perhaps it could still be fixed with more information, like a log file and stuff? (I assume that's why this was marked as invalid, right p455w0rd? Not having enough information?)

**Comment by p455w0rd** [comment]
indeed @macks2008

**Comment by Twisted-Code** [comment]
@Pixel1011 if it happens again, mind grabbing some extra information like a log file and stuff so p455w0rd has something to go by in trying to fix it? Ideally a copy of your player.dat while you have the storage cell containing it in your inventory would also help, or so I would imagine.
And of course I'll do the same if it happens to me.

**Comment by Pixel1011** [comment]
alright, might just try to make it happen again

**Comment by Pixel1011** [comment]
[Danknull.zip](https://github.com/p455w0rd/DankNull/files/3713570/Danknull.zip)
alright here you go
it has both log files and the player.dat with cell

**Comment by p455w0rd** [comment]
so it appears there's a sync issue..still no idea why its happening, but I can reproduce this. Shift-clicking/shift-double-clicking gets it back into my inventory, although I do have to close the terminal GUI and reopen before it updates..this is truly odd

**Comment by p455w0rd** [comment]
As a side effect of what I did to fix #79, this seems to also be fixed. Let me know if you experience this after [the latest update](https://www.curseforge.com/minecraft/mc-mods/dank-null/files/2829709). You will also need [this version of p455w0rdsLib](https://www.curseforge.com/minecraft/mc-mods/p455w0rds-library/files/2829707).
