### ISSUE TITLE
Dank Null PacketConfigSync$Handler crash

### ISSUE THREAD

**Issue by happybandit360** [p455w0rd/DankNull#237]
I have had two testers send me crash reports with a similar stack trace related to Dank Null

Report 1: https://gist.github.com/PseudoFyre/a385c43a510926ac560ac6b74d3d0fd1
Report 2: https://gist.github.com/happybandit360/615824ef706267dae58c4f9f80897808

Both crashes were experienced immediately upon logging into the server world for the first time. Neither had a Dank Null in their inventory.

/dank/null version 1.12.2-1.7.89
p455w0rd's Library version 1.12.2-2.3.161

We have had many other players who have not experienced this issue at all.

**Comment by p455w0rd** [comment]
is the server running 1.7.89 as well?

**Comment by happybandit360** [comment]
Yes. Double checked that first.

**Comment by BedrockLegends** [comment]
We get the same error, both mod and server match

**Comment by BedrockLegends** [comment]
https://github.com/p455w0rd/DankNull/issues/240

**Comment by knoxhack** [comment]
🤔

**Comment by Drecondius** [comment]
I am having a similar issue, there isn't a crash thankfully, but I don't have a /dank/null in my inventory.
Both jars match sadly.

https://paste.dimdev.org/lavuxibeta.mccrash

1.12.2 Enigmatica 2 Expert
mod version : 1.7.89
Forge version : 14.23.5.2847

can't paste a full stacktrace as the game is still running due to vanilla fixes.

**Comment by ghost** [comment]
Is the dev version that this is fixed in available for download?

**Comment by Hamilegit** [comment]
I am also having this problem on logging into my server
