### ISSUE TITLE
Docking Station Duplicates Freshly Crafted /Dank/Nulls

### ISSUE THREAD

**Issue by DimitriBarronmore** [p455w0rd/DankNull#262]
Freshly crafted /dank/nulls are created with no NBT tags. When the player attempts to place a /dank/null on a docking station the mod first marks the station as having a /dank/null docked, and **then** searches the NBT to find the /dank/null's current inventory. 

This happens before the /dank/null is removed from the player's inventory. Currently, if the mod fails to find the appropriate tag on said /dank/null, the interaction silently fails. The /dank/null is not removed from the player's inventory, but it remains on the docking station with no model. This allows for infinite duplication of /dank/nulls that have never had items placed in them. 

https://paste.dimdev.org/cuqigewuye.mccrash

**Comment by Twisted-Code** [comment]
Thanks to your realization that it's problem with missing NBT, I was able to make a workaround recipe script using CraftTweaker. For those interested, here it is: 
[fix dank.zs.txt](https://github.com/p455w0rd/DankNull/files/4396172/fix.dank.zs.txt) (just remember to change the file extension back to zs. I had to make it .txt in order to upload it here)

**Comment by cjm721** [comment]
Fixed by #263
