### ISSUE TITLE
Bug with MK VI Dank Null

### ISSUE THREAD

**Issue by chrisa64** [p455w0rd/DankNull#310]
Playing in PO3, and whenever I try to craft the dank null mk VI, it causes game to become unresponsive. Only way to exit is ALT-F4 or end task in task manager. I have checked the crash report folder but no report is made. Does anybody else have this issue?

Dank Null Version: MK VI
p455w0rds Lib Version:1.12.2-2.3.161
Forge Version:14.23.5.2847

Steps To Reproduce:
1.Create Dank Null MK I - V
2.Create Dank Null VI
3.Game Crash

Was this tested on Single Player or Server (or Both)? Server

Was this tested with just Dank Null installed? No

**Comment by cjm721** [comment]
@Cazadorsniper (PO3 author) was unable to reproduce. I assume it is either something with your instance or server's state. Without me being able to reproduce I cannot fix this. If you want you can try and grab a thread dump instead of just alt-f4ing and post that.

(Also MK VI is not a dank null version)
