### ISSUE TITLE
[1.12.2] /dank/null Order

### ISSUE THREAD

**Issue by Morpheus1101** [p455w0rd/DankNull#32]
So i been thinking of perhaps changing up the sequence for the /dank/null to be
Iron, Redstone, Gold, Lapis, Diamond, Emerald

**Comment by p455w0rd** [comment]
redstone before iron was intentional..basically do at least a LITTLE bit of actually work first lol...gold/lapis..lapis is easier to find than gold so i don't see a point there...I do want to completely rework the GUI code at some point to use a single texture and just draw the colors as needed via GL..but after giving it some thought, this order will remain unless you can give a compelling reason to do such a thing..i'll leave it open and let you decide whether or not to close the issue :)
