### ISSUE TITLE
[1.12] Mod Interaction w/ SwingThroughGrass

### ISSUE THREAD

**Issue by SnowShock35** [p455w0rd/DankNull#35]
Hi,

This bug is to both @p455w0rd and @Exidex as the issue occurs when only both your mods are present on the client when connecting to a dedicated server .

#### Issue Details

* Minecraft 1.12.2
* Minecraft Forge 14.23.1.2555
* CodeChicken Lib 1.8+ 3.1.3.313
* p455w0rd's Library 2.0.24
* /dank/null 1.0.14
* SwingThroughGrass 1.2.1

#### Issue Description

When connecting to a dedicated server for the first time,  the player will be unable to break tall grass and other decorative plant life blocks. Not only this, the player has an increased destroy speed when attempting to break the plant. No obvious solution presents itself - even re-logging and when the server restarts the same behaviour occurs once more. Just after a certain time (which is random from what I can tell.) the issue no longer occurs and everything is fine once more. Also, it's worth noting that this is **not** spawn protection causing the issue. 

I have little to add to this, on what can only be described as a rather peculiar, issue.

#### Issue Media

latest.log - client
https://pastebin.com/DpYstaPZ

latest.log - server
https://pastebin.com/hyTLLwS0

fml-server-latest.log
https://pastebin.com/Z4gSh2E3

fml-junk-earlystartup.log
https://pastebin.com/7qvBeNUd

the issue
https://ss.blamesnow.co.uk/2017/12/1512723164-b54f7d53.gif

**Comment by p455w0rd** [comment]
bug found! 
- SwingThroughGrass check for any Entity (including non-mobs like EntityItems)
- it also doesn't do a check for FakePlayer (/dank/null relies on this in 1.11+)
- after the coming update even checking for FakePlayer will not be sufficient since another mod (FTBUtils) is disabling stuff via traditional FakePlayers, so my new custom FakePlayer must be special-cased

For now @SnowShock35 and I have come up with a solution. If @Exidex wishes to work with me on this, I'm more than open to helping get this resolved :)

Thanks @SnowShock35 !

**Comment by Exidex** [comment]
Thanks @SnowShock35 and @p455w0rd for reporting and finding a solution for the issue. It is now fixed

**Comment by p455w0rd** [comment]
didn't mean to close lol..ima leave this open till i get a chance to push next update on my end
