### ISSUE TITLE
/Dank/Null inventory placement

### ISSUE THREAD

**Issue by Zedrimar** [p455w0rd/DankNull#9]
So this is a bit of an issue.... its really annoying. if you do not place an item EXACTLY in the middle of a slot when in the GUI for the /Dank/Null (I was testing with tier 5 but from what I know, it's for all of them), the item gets tossed out. This is not specific to any item that is in the item itself, this includes inventory. So if I move an item magnet but do not put it within the tiny little space that is considered the "slot" it gets tossed out.... Normal inventory doesn't have this problem :/

**Comment by Zedrimar** [comment]
it seems that the slots may be skewed a bit as the left side is fine but if put in the right side of the slot, it gets tossed

**Comment by p455w0rd** [comment]
ooo...ok..i do know what you are talking about..i just never thought about that..also..you can shift-click :)..but THANK YOU (if this is the case with the detection being off)...the slots themselves are fine..it's the mouse clicking that seems off..just took you putting it like that for me to realise it ..seriously..I hope this is the issue..if so, it shoudn't be a hard fix..

**Comment by Zedrimar** [comment]
yeah, sorry about the wording.... I am literally testing this as I write it :P but yeah, it just acts like there is empty space between slots so it chucks the item

**Comment by Zedrimar** [comment]
Ok, random question though, any suggestions for learning Java? I took a course back in highschool but it barely covered anything besides basic functions and not much else.

**Comment by p455w0rd** [comment]
Java is not JavaScript...I only say this because you referenced 'functions' which are used in JavaScript where Java uses "methods". As for learning it, I learned HTML, JavaScript, Perl, and PHP first. This made learning subsequent languages mush easier. The best way is to just go at it in my opinion. Start with a sample mod and go from there. There are plenty of amazing helpful people in the modded Minecraft community...but there are jerks as well. If I were to suggest anything it would be googling specific ppl's name followed by "Tutorial". Some name would be "McJty, bedrockminer, and coolAlias"..there are many more..but McJty himself helped me get started when I was creating my first mod, Wireless Crafting Terminal. I had no prior Java knowledge at that point. I only had a general understanding of Object-Oriented Programming in general. I'm a 31 year old high school drop out. If I can do it, you can too :)

**Comment by Zedrimar** [comment]
it was some class on "codeHS" so yeah, probably was JS. it just had basic stuff like for loops and all that, nothing really deep besides some psuedo code to learn off of :/

**Comment by Zedrimar** [comment]
Thank you though, I will go take a look. There was some online class that I saw that explained methods and all that but not deeply... it was like: here is a method, here is where you type in "method" and not much more (just the most basic of the basic)

**Comment by p455w0rd** [comment]
are you available to join my discord (http://p455w0rd.net/discord) and run a test build and see if you still experience any issues?

**Comment by p455w0rd** [comment]
nvm..I'm fairly certain the issue is fixed..building and pushing to Curse now

**Comment by Zedrimar** [comment]
yeah its fixed now, thanks! :3
