### ISSUE TITLE
player's interaction with /dank/null affecting other players' /dank/nulls

### ISSUE THREAD

**Issue by NoHotLiquids** [p455w0rd/DankNull#94]
I'm running a LAN Minecraft game (using the single player's 'open to LAN' button).
We are using the FTB Revelations ver.1.60, in case it is a quirk of this pack. 

If I am holding my Dank MK III and then the other player changes their Dank MK III's selected block, my Dank will change to scroll through my block list for the same number of inputs as the other client did.
i.e: -my list is [stone, dirt, wood] and i have stone selected, 
if the other client scrolled though 3 of their items I would be at stone again.

--this only happens if I have my Dank in my hand, 
--also I cannot control the other client's Dank in the same matter.

**Comment by p455w0rd** [comment]
this is definitely the first time I'm hearing about this..I am recoding all of the network communication stuff in the mod as there are a bunch of other bugs I've found in multiplayer (specifically when 2 players access the same docking station GUI there is a bad desync that happens..if you have TOP installed you can see that the info is indeed being sent to the server, but for some reason not synced back to clients properly within the mod)..so this will be fixed as soon as I get all the new packet handling code finished..I have no ETA atm cuz midterms..but hopefully sooner rather than later..i'd love to have this tested in your environment (not many people use the open to LAN option) prior to my final push to curseforge..join my discord if you wanna know when I'm going to push a new version..i'll post a dev candidate for people to test before the final push to CF...thanks for reporting

**Comment by NoHotLiquids** [comment]
That's fine, grades do come first.
I've just done some more tests for you and if you have any others you want us to try just let us know.

so I made a Dank Mk I the other client is still on a Dank Mk III, they could still interact with my Dank but this time it loses the selected block render and it ceases to place blocks, it is fix-able by opening the GUI and selecting the block from there. still only a one way interaction.

May also think about joining discord at some point.

**Comment by KollinsPlays** [comment]
I don't know if this is the same, but in a single player world when I place 1 dank/null in a dock and it is pulling items out, the other dank/null in my hand shows the contents of the docked one instead of it's own contents.

**Comment by p455w0rd** [comment]
postponed since the docking station GUI is currently disabled, the I'll be reimplementing the GUI code in the next update

**Comment by robinbuts** [comment]
I also play "open to lan" with my buddy. We play a stoneblock modpack. i had a tier 5 dank he had a gold dank. My dank changed to a gold one also and all i had inside was lost. Hope u will be able to fix this soon-ish. 
love the dank so would be nice if we can use this again. untill then its basicly broken and not suitable for anything :(
