### ISSUE TITLE
/dank/null completely breaks Astral Sorcery progression

### ISSUE THREAD

**Issue by Hazmatik** [p455w0rd/DankNull#96]
So if you take any of the rock/celestial crystals from the Astral Sorcery mod and put it in a /dank/null any more crystals you pick up will be changed to the same attributes as the first one you placed in (size, purity, and cutting) so you could put a perfect crystal into the /dank/null and just keep making perfect crystals completely circumventing the system in place by Astral Sorcery to improve the crystals.

**Comment by Rixxaw** [comment]
Seriously?  that seems like a problem with Astral Sorcery.  Seems like you could do the same thing with Drawers?

**Comment by p455w0rd** [comment]
@Hazmatik i think this is the same issue referenced in #95. So even though it's a different item, it's due to NBT data not being compared. Therefore, I'm going to mark this as duplicate and close it. Just know i'm not saying you didn't research properly or anything. It's purely that it's the same bug affecting both issues. You were correct to create a new issue. I have fixed #95 now, but I still have a lot to do before the update. Thanks for the report!
